name: rnaseq-test
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - bioconda::fastqc=0.11.9
  - bioconda::cutadapt=3.0
  - bioconda::pear=0.9.6
  - bioconda::sortmerna=2.1b
  - bioconda::seqtk=1.3
  - bioconda::star=2.7.7a
  - bioconda::gffread=0.12.1
  - conda-forge::parallel=20201122
